name: gps
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  camera: ^0.11.0+2
  vibration: ^1.7.0
  path_provider: ^2.1.4
  image_gallery_saver: "^2.0.3"
  gallery_saver: ^2.3.1
  audioplayers: ^5.1.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    
